before_script:
  - export BUILD_PREFIX=build${CI_PIPELINE_ID}
  - export COMPOSE_PROJECT_NAME=${BUILD_PREFIX}yii2pages
  - cd tests

stages:
  - test
  - report
  - cleanup

test:
  stage: test
  script:
    - set +e
    - make build
    - make up
    - make setup
    - make run-tests || $TESTS_EXIT_CODE=0
    - set -e
    - mv codeception/_output /tmp/${BUILD_PREFIX}
    - exit $TESTS_EXIT_CODE

lint:
  stage: test
  script:
    - export COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}lint
    - make build
    - make lint
  allow_failure: true

report:
  stage: report
  script:
    - mv /tmp/${BUILD_PREFIX} _output
  artifacts:
    paths:
      - tests/_output/
  when: always

cleanup:
  stage: cleanup
  script:
    - make clean
  when: always

